# Generated by Django 5.1.7 on 2025-04-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='业务线')),
            ],
            options={
                'verbose_name': '业务线表',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机房')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
            ],
            options={
                'verbose_name': '机房表',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status_id', models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1, verbose_name='设备状态')),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜号')),
                ('cabinet_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜中序号')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名称')),
                ('os_platform', models.CharField(blank=True, max_length=16, null=True, verbose_name='主机系统')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='主机系统版本')),
                ('sn', models.CharField(db_index=True, max_length=64, verbose_name='主板SN号')),
                ('manufacture', models.CharField(blank=True, max_length=64, null=True, verbose_name='主板制造商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='主板型号')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU个数')),
                ('cpu_physical_count', models.IntegerField(blank=True, null=True, verbose_name='CPU物理个数')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('latest_data', models.DateField(auto_now=True, null=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.businessunit', verbose_name='所属业务线')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.idc', verbose_name='IDC机房')),
            ],
            options={
                'verbose_name': '服务器表',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='网卡名称')),
                ('hwaddr', models.CharField(max_length=64, verbose_name='网卡mac名称')),
                ('ipaddrs_netmask', models.CharField(max_length=256, verbose_name='网卡ip地址和子网掩码')),
                ('up', models.BooleanField(default=False, verbose_name='网卡状态')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_list', to='repository.server')),
            ],
            options={
                'verbose_name': '网卡表',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='内存槽位')),
                ('manufacture', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存制造商')),
                ('model', models.CharField(max_length=64, verbose_name='内存型号')),
                ('capacity', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存容量GB')),
                ('sn', models.CharField(db_index=True, max_length=64, verbose_name='内存SN号')),
                ('speed', models.CharField(blank=True, max_length=16, null=True, verbose_name='内存速度')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_list', to='repository.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '硬盘表',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.server')),
            ],
            options={
                'verbose_name': '错误日志表',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=8, verbose_name='硬盘槽位')),
                ('model', models.CharField(max_length=32, verbose_name='硬盘型号')),
                ('capacity', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘容量GB')),
                ('pd_type', models.CharField(max_length=32, verbose_name='硬盘类型')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='repository.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '硬盘表',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='repository.server')),
            ],
            options={
                'verbose_name': '资产记录表',
            },
        ),
    ]
