# Generated by Django 5.1.7 on 2025-04-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_rename_manufacture_server_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
