# Generated by Django 5.1.7 on 2025-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_rename_manufacture_memory_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='hwaddr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='网卡mac名称'),
        ),
    ]
