# Generated by Django 5.1.7 on 2025-05-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_nic_hwaddr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_change_list', to='repository.server'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_list', to='repository.server', verbose_name='服务器'),
        ),
    ]
