# Generated by Django 5.1.7 on 2025-05-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(max_length=100, verbose_name='url路径')),
                ('reverse_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='url名称')),
                ('menu_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单名称')),
                ('is_changelist', models.BooleanField(default=False, verbose_name='是否是二级菜单')),
                ('parent_url_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('permission', models.ManyToManyField(to='rbac.permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户名称')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='用户密码')),
                ('role', models.ManyToManyField(to='rbac.role')),
            ],
        ),
    ]
