# Generated by Django 5.1.7 on 2025-05-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='url标题'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_url_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='归属url路径'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='rbac.permission', verbose_name='角色权限'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(to='rbac.role', verbose_name='用户角色'),
        ),
    ]
