# Generated by Django 5.1.7 on 2025-05-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_title_alter_permission_parent_url_pattern_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属一级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_url_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='所属二级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='reverse_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='reverse名称'),
        ),
    ]
